version: "2.0"
nlu:
- intent: mood_great
  examples: |
    - I am great
    - so so perfect
    - extremely good
    - great
    - I am going to save the world
    - so good
    - I am amazing
    - super stoked
    - wonderful
    - feeling like a king
    - so perfect
- intent: mood_unhappy
  examples: |
    - my day was horrible
    - I'm so sad
    - not good
    - so sad
    - I don't feel very well
    - not very good
    - unhappy
    - so saad
    - extremly sad
    - sad
    - super sad
- intent: bot_challenge
  examples: |
    - are you artificial intelligence
    - are you sure that you're a bot?
    - aren't you a bot
    - are you a robot
    - are you real
    - are you a rasa bot?
    - bot?
    - are you robot
    - am i speaking to an ai?
    - are you a chatbot
    - are you virtual?
    - are you really a bot
    - are you a human or a bot?
    - are you an ai?
    - are you ai
- intent: thankyou
  examples: |
    - thank you
    - good job bot
    - great
    - thanks you
    - Oh thats good!
    - thanks
    - thanks for your information
    - thanks f
    - I see, thanks
    - Thanks!
    - Awesome, you are a good bot!
    - okay thank you
    - thanks for the help
    - thankyou
    - thx
- intent: help
  examples: |
    - what do you do?
    - hep me
    - how do I use this
    - help please
    - help, what do you do
    - hello what can you do for me
    - what can I ask you?
    - help me
    - What are the things that you can do?
    - can you do anything else?
    - help
    - what can you help me with?
    - what can you do?
    - help?
    - cool! can I do something else here?
    - can you help me?
- intent: greet
  examples: |
    - goodevening
    - hello are you still there
    - they call me Sara
    - hello, my name is Sara
    - Sara talking!
    - good afternoon
    - hey there
    - begin
    - This is Sara
    - Hey, this is Jane
    - good evening
    - hey dude
    - good morning
    - Carla here!
    - let's go
    - hello there
    - start
    - hi
- intent: deny
  examples: |
    - i'm not sure
    - i guess it means - no
    - no thanks
    - i decline
    - i dont want to
    - i'm afraid not
    - i don't want to
    - nevermind
    - i dont want to accept :P lol
    - I don't think so
    - no way
    - no
    - i don't think so
    - Nothing!
    - I dunno
    - not really
    - never
    - n
- intent: ask_transfer_charge
  examples: |
    - are there any transaction fees or charges I should know about?
    - is there a charge when I send money to someone
    - I sent money to my friend will I be charged extra for that
    - if I send money to someone will I be charged extra for that?
    - Will I be charged for transferring money
    - is there a xfer fee
    - what am I charged upon money transfer
    - how much is the transfer fee
    - what is the percentage fee for transactions to another person
    - will i be charged for a transaction?
    - whats the xfer price for this account
    - okay but how much to move this money?
    - are you gonna bill me for this exchange
    - Is there a charge
    - is there a transfer charge?
    - do xfers cost something?
    - is there a transfer fee
- intent: check_recipients
  examples: |
    - who exactly am I able to send money to
    - Show me my list of recipients
    - Who can I transfer money to?
    - Who is a valid payee
    - Who all can I transfer money to?
    - Show me people I can send money to
    - whats my recipient list
    - if I want to transfer money can i send it to anyone
    - show me my money sending list
    - Who are my known recipients
    - tell me who I can share my money with
    - Who can I send money to?
    - who is in my list of kown recipients?
    - Show the recipient list
    - Okay. Who can I transfer money to then?
    - Who is on your list?
    - who can I transfer money to?
    - can I see the list of known recipients?
- intent: out_of_scope
  examples: |
    - Fridge Isn't Running
    - stuffff
    - Can you please send me an uber
    - order a pizza
    - what the weather today ?
    - tell me a joke
    - Can I get a hamburger?
    - what year is it
    - I want a pizza
    - Can YouTube talk?
    - Can you give me your datacenter's password?
    - what is the weather today
    - ofif fsdfafsfs
    - my tv isn't working
    - I want to order a pizza
    - what is the square root of 5
    - what is the weather
    - tbalbiiiiz
    - my washing machine isn't working
    - Can you give me your datacenter's password
    - hows the weather
- intent: goodbye
  examples: |
    - bye bye
    - ok i gtg
    - quit
    - good bye
    - bye was nice talking to you
    - bye udo
    - see you later
    - stop
    - catch you later
    - i'm done
    - Thanks a lot. See ya later
    - bye!
    - goodbye
    - and thats all thank you and good bye
    - bye bye bot
    - BYEE
    - Adios
    - bye
    - farewell
    - ciao
    - cya
    - bye for now
    - good bye rasa bot!
    - good night
- intent: affirm
  examples: |
    - ok
    - alright
    - y
    - yess please
    - Yep!
    - indeed
    - Yes I do
    - Yep that's fine
    - of course
    - yes
    - Yes please
    - Ok
    - Yeah sure
    - yes please
    - correct
    - yup
    - cool,
    - Yes, I accept
    - Yeah
    - yes plz
    - Yea
    - that sounds good
    - Sure
    - okay
    - yeah
    - Yes please!
    - yes...
    - ye
- intent: pay_cc
  examples: |
    - Pay my [discover](credit_card)
    - I want to pay my [iron bank](credit_card) bill
    - I want to pay my [credit card](account_type)
    - could I pay off my [credit card]{"entity": "account_type", "value": "credit"}?
    - I want to pay my [visa](credit_card) bill
    - I want to pay my [MasterCard](credit_card) bill
    - I want to pay 100 dollars toward my [Emblem](credit_card) [card](account_type), tomorrow
    - I guess it is. Since it's so much, let's pay off my [credit](account_type)
    - Pay my [visa](credit_card)
    - pay off my [credit card]{"entity": "account_type", "value": "credit"}
    - I would like to pay the [minimum balance](amount-of-money) on my [embelm](credit_card) [card](account_type)
    - pay a bill
    - I want to pay my [justice bank](credit_card) bill
    - can I pay my [card]{"entity": "account_type", "value": "credit"}?
    - I want to pay off my [credit card](account_type)
    - pay 100 towards [emblem](credit_card) [card](account_type), tomorrow
    - Please schedule  a payment towards my [credit card](account_type) for April 12th
    - i need to pay off my [emblm](credit_card) [credit card](account_type)
    - can you help me pay the [current balance](amount-of-money) on my [credit card](account_type)
    - I want to pay $500 on my [emblem](credit_card) [credit card](account_type) on Sunday
    - i want to pay off my [emblem](credit_card) [credit card](account_type)
    - id like to pay my bill
    - I want to pay my [credit card](account_type) bill
    - I want to pay my [card](account_type)
    - I would also like to pay my [visa](credit_card) bill
    - Let's pay that [credit card]{"entity": "account_type", "value": "credit"} bill
    - i want to pay my [current balance](amount-of-money) on my [emblem](credit_card) [credit card](account_type)
    - i would like to pay $1200 to my [credit card]{"entity": "account_type", "value": "credit"}
    - Can I schedule a payment towards my [credit card](account_type) for tomorrow?
    - I want to pay my [current balance](amount-of-money) on my [emblem](credit_card) [credit card](account_type) today
    - I want to pay my [current balance](amount-of-money) on my [embelm](credit_card) [credit card](account_type)
    - i wanna pay my [credit card]{"entity": "account_type", "value": "credit"}
- intent: transfer_money
  examples: |
    - pay [Mona](PERSON) $60
    - I want to pay [Bert](PERSON)
    - send $50 to [john jacob](PERSON)
    - i want to transfer money to [Latisha](PERSON)
    - Ok pay [Emma](PERSON)
    - i want to transfer $100 to my [daughter](PERSON)
    - I would like to transfer money to [Philipp](PERSON)
    - Ahh, okay so I want to make a transfer to [Bob](PERSON).
    - I want to pay [Paula Handy](PERSON)
    - Hi I like to send money to [John](PERSON)
    - I need to pay a friend.
    - I need to transfer money
    - can I transfer money to my [mom](PERSON)
    - can I transfer money to [Kyle Gardner](PERSON)?
    - Can I transfer money to a friend?
    - I need to send money to my kid
    - transfer money to [ethan oswald](PERSON)
    - Pay [Percy](PERSON) $50
    - i want to transfer $400 to [Akela](PERSON)
    - i want to transfer $100 to [Jane smith](PERSON)
    - I need to make an urgent transfer to [Bob](PERSON), can you do it?
    - can i transfer money to [Sally](PERSON)
    - I want to pay someone
    - pay my friend
    - i mean i want to transfer money
    - I need to transfer money to my co-worker who paid for lunch
    - transfer money to [sara](PERSON)
    - transfer $60 to [Jason Jacob](PERSON)
    - I'd like to send 50$ to [John](PERSON)
    - Please transfer 50 dollars to [Andreas](PERSON)
    - pay [Lisa](PERSON) please
    - I want to pay [John](PERSON)
    - pay Katy Parrow $40 please
    - transfer money
    - Pay [Karen](PERSON) 60 Euros
    - can I pay someone
    - pay [Evan Oslo](PERSON)
    - Pay $50 to [Pat](PERSON)
    - I want to transfer money
    - I need to transfer money to a friend
- intent: check_balance
  examples: |
    - whats my account [balance](amount-of-money)
    - what's my account [balance](amount-of-money)?
    - Whats the [balance](amount-of-money) on my [credit](account_type) account
    - What is my [emblem](credit_card) [balance](amount-of-money)?
    - Can you tell me my account [balance](amount-of-money)?
    - What's my [credit](account_type) account
    - What's the [balance](amount-of-money) on the [justice bank](credit_card) account
    - Show me my [iron bank](credit_card) [balance](amount-of-money)
    - What's my [justice bank](credit_card) [balance](amount-of-money)
    - whats my [emblm](credit_card) [card](account_type) [balance](amount-of-money)?
    - what's my [balance](amount-of-money)?
    - what's my [emblm](credit_card) account [balance](amount-of-money)?
    - what is my account [balance](amount-of-money)
    - what is my [bank](account_type) account [balance](amount-of-money)
    - check my [credit card]{"entity": "account_type", "value": "credit"} [balance](amount-of-money)
    - what's my account [balance](amount-of-money)
    - Hi, I need to know how much money is in my [checking](account_type) account
    - How much do I have on that account?
    - Show me my [credit](account_type) accounts
    - Yeah, I like coffee 👀 But how much money do I have?
    - What's my [credit card](account_type) [balance](amount-of-money)
    - How much money have i spent lately>
    - what places have I spent money?
    - Wait, I'll have to check my balance first. Can you do that please?
    - what's my [bank](account_type) account [balance](amount-of-money)
    - Show me my [credit card](account_type) [balance](amount-of-money)
    - How much money is on my account?
    - Yeah, I know 😀 Since it's so nice: How much money do I have?
    - check my [credit card]{"entity": "account_type", "value": "credit"} [balance](amount-of-money) [first](account_type)
    - what's my [credit card](account_type) account [balance](amount-of-money)?
    - What's my [balance](amount-of-money)?
    - How much money is on my [bank](account_type) account?
    - I should check my [credit card]{"entity": "account_type", "value": "credit"} [balance](amount-of-money) [first](account_type)
    - whats my [current balance](amount-of-money)
    - what's my [embelm](credit_card)'s [card](account_type) [balance](amount-of-money)?
    - How much money do I have?
    - Balance please
    - What is my [emblem](credit_card) [card](account_type) [balance](amount-of-money)?
    - what's my [current balance](amount-of-money)?
    - What's my [credit](account_type) [balance](amount-of-money)
    - How much money do I owe on my [credit cards](account_type)
    - what's my [bank](account_type) account [balance](amount-of-money)?
    - Hello, I would like to know how much money is in much money is in my account
    - How much money is left on that account?
- synonym: credit
  examples: |
    - credit card
    - card
    - credit cards
    - credit account
    - credit accounts
    - cards
    - credit card account
- synonym: emblem
  examples: |
    - emblm
    - embelm
    - Emblem
- synonym: current balance
  examples: |
    - balance
    - full
    - full balance
